module.exports = {
	rules: {
		'string-quotes': ['single', { severity: 'warning' }],
		'color-hex-case': 'lower',
		'color-hex-length': 'short',
		'color-no-hex': null,
		'color-no-invalid-hex': true,
		'color-named': ['never', { severity: 'warning' }],
		'number-leading-zero': 'always',
		'number-max-precision': 5,
		'number-no-trailing-zeros': null,
		'number-zero-length-no-unit': [true, { severity: 'warning' }],
		'function-blacklist': null,
		'function-calc-no-unspaced-operator': true,
		'function-comma-newline-after': null,
		'function-comma-newline-before': null,
		'function-comma-space-after': 'always',
		'function-comma-space-before': 'never',
		'function-linear-gradient-no-nonstandard-direction': true,
		'function-parentheses-newline-inside': null,
		'function-parentheses-space-inside': 'never',
		'function-url-quotes': ['always', { severity: 'warning' }],
		'function-whitelist': null,
		'function-whitespace-after': 'always',
		'value-no-vendor-prefix': [true, { severity: 'warning' }],
		'value-list-comma-newline-after': null,
		'value-list-comma-newline-before': null,
		'value-list-comma-space-after': 'always',
		'value-list-comma-space-before': 'never',
		'unit-blacklist': null,
		'unit-whitelist': null,
		'property-blacklist': null,
		'property-no-vendor-prefix': [true, { severity: 'warning' }],
		'property-unit-blacklist': null,
		'property-unit-whitelist': null,
		'property-whitelist': null,
		'custom-property-no-outside-root': [true, { severity: 'warning' }],
		'custom-property-pattern': null,
		'declaration-bang-space-after': 'never',
		'declaration-bang-space-before': 'always',
		'declaration-colon-newline-after': ['always-multi-line', { severity: 'warning' }],
		'declaration-colon-space-after': 'never',
		'declaration-colon-space-before': 'never',
		'declaration-no-important': null,
		'block-no-single-line': [true, { severity: 'warning' }],
		'declaration-block-semicolon-newline-after': null,
		'declaration-block-semicolon-newline-before': null,
		'declaration-block-semicolon-space-after': 'always-single-line',
		'declaration-block-semicolon-space-before': 'never',
		'declaration-block-single-line-max-declarations': null,
		'block-closing-brace-newline-after': 'always',
		'block-closing-brace-newline-before': 'always-multi-line',
		'block-closing-brace-space-after': null,
		'block-closing-brace-space-before': 'always-single-line',
		'block-no-empty': [true, { severity: 'warning' }],
		'block-opening-brace-newline-after': 'always-multi-line',
		'block-opening-brace-newline-before': null,
		'block-opening-brace-space-after': 'always-single-line',
		'block-opening-brace-space-before': 'always',
		'selector-class-pattern': null,
		'selector-combinator-space-after': 'always',
		'selector-combinator-space-before': 'always',
		'selector-id-pattern': null,
		'selector-no-attribute': null,
		'selector-no-combinator': null,
		'selector-no-id': null,
		'selector-no-type': [true, { severity: 'warning' }],
		'selector-no-universal': [true, { severity: 'warning' }],
		'selector-no-vendor-prefix': [true, { severity: 'warning' }],
		'selector-pseudo-element-colon-notation': null,
		'selector-root-no-composition': true,
		'selector-list-comma-newline-after': 'always-multi-line',
		'selector-list-comma-newline-before': null,
		'selector-list-comma-space-after': 'always-single-line',
		'selector-list-comma-space-before': 'never',
		'rule-nested-empty-line-before': ['always-multi-line', { severity: 'warning' }],
		'declaration-block-no-duplicate-properties': [true, { ignore: ['consecutive-duplicates'] }],
		'declaration-block-no-shorthand-property-overrides': true,
		'rule-non-nested-empty-line-before': ['always', { severity: 'warning' }],
		'declaration-block-properties-order': null,
		'declaration-block-trailing-semicolon': 'always',
		'root-no-standard-properties': null,
		'media-feature-colon-space-after': 'never',
		'media-feature-colon-space-before': 'never',
		'media-feature-name-no-vendor-prefix': true,
		'media-feature-range-operator-space-after': 'always',
		'media-feature-range-operator-space-before': 'always',
		'custom-media-pattern': null,
		'media-query-parentheses-space-inside': 'never',
		'media-query-list-comma-newline-after': 'always-multi-line',
		'media-query-list-comma-newline-before': null,
		'media-query-list-comma-space-after': 'always-single-line',
		'media-query-list-comma-space-before': 'never',
		'at-rule-empty-line-before': ['always', {
			except: ['blockless-group', 'all-nested']
		}],
		'at-rule-no-vendor-prefix': [true, { severity: 'warning' }],
		'comment-empty-line-before': null,
		'comment-whitespace-inside': 'always',
		'indentation': ['tab', { indentInsideParens: ['once'] }],
		'max-line-length': null,
		'max-empty-lines': [1, { severity: 'warning' }],
		'no-eol-whitespace': true,
		'no-missing-eof-newline': true
	}
};
